-- =============================================================================
-- INSTANT FUNDING — mise a jour du listing
-- =============================================================================
-- Source : "Prop Firm Listing DATA - Instant Funding.docx", date du 27 aout 2026,
-- fourni par Instant Funding (partners@instantfunding.com).
-- Donnees partenaire, non verifiees independamment contre le site officiel.
--
-- A PASSER DANS CET ORDRE. L'etape 0 n'est pas optionnelle : l'etape 2 supprime
-- des lignes.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- ETAPE 0 — SAUVEGARDE. Exporter le resultat en CSV avant d'aller plus loin.
-- -----------------------------------------------------------------------------
select * from prop_firm_challenges where firm_slug = 'instant-funding';
select * from prop_firms            where slug      = 'instant-funding';


-- -----------------------------------------------------------------------------
-- ETAPE 1 — Niveau firme
-- -----------------------------------------------------------------------------
-- affiliate_url, website_url, discount_code, discount_percent, verdict, headline
-- et les colonnes editoriales ne sont PAS touches : le document n'en parle pas.
update prop_firms set
  name               = 'Instant Funding',
  founded_year       = 2021,
  headquarters       = '30 Old Bailey, London, EC4M 7AU, United Kingdom',
  min_payout         = 25,
  min_price          = 25,
  profit_split       = 80,
  payout_frequency   = 'on-demand',
  drawdown_type      = 'Varies by program: Smart, Static, Trailing and End-of-Day trailing',
  scaling_max        = '$1,280,000 per account on Instant Funding, Instant Funding GO and Instant Funding Clarity; 100% of starting balance on all other programs',
  max_allocation     = '$1,000,000 combined cap across all accounts, on starting balance only',
  commissions        = 'Two models at the same price: Standard (commission-free) or RAW (tighter spreads, commissions apply). RAW: FX $5/lot, Metals $5/lot, Commodities $2/lot, Crypto $1/lot, Indices approx. $2/lot.',
  refund_policy      = 'Challenge and account fees are not refunded. After a breach a Retry button stays in the dashboard for 60 days and opens a discounted checkout for the same product; it creates a new account rather than restoring the breached one.',
  time_limit         = 'None, except IF1 (24 hours from the first trade, 48 with the add-on). Accounts auto-close after 60 days without a trade.',
  consistency_rule   = 'Varies by program, from none to a 15% best-day cap. See each program.',
  is_regulated       = false,
  regulation_details = null,
  updated_at         = now()
where slug = 'instant-funding';


-- -----------------------------------------------------------------------------
-- ETAPE 2 — Programmes. Remplacement complet.
-- -----------------------------------------------------------------------------
-- Le DELETE est necessaire : Two-Phase, Two-Phase Micro, One-Phase Crypto et
-- IF Micro Crypto ne sont plus vendus. Un upsert les laisserait affiches.
-- Le tout dans une transaction : en cas d'echec de l'INSERT, rien n'est perdu.
begin;

delete from prop_firm_challenges where firm_slug = 'instant-funding';

insert into prop_firm_challenges (
  id, slug, name, firm_name, firm_slug, account_size, steps, max_drawdown, max_daily_loss, phase1_profit_target, drawdown_type, max_loss_type, profit_split, price, discounted_price, payout_frequency_description, consistency_rule, allows_ea, allows_scalping, allows_news_trading, billing_period, risk_unit
) values
  (gen_random_uuid(), 'instant-funding-625', 'Instant Funding $625', 'Instant Funding', 'instant-funding', '$625', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 44, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-1250', 'Instant Funding $1,250', 'Instant Funding', 'instant-funding', '$1,250', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 84, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-2500', 'Instant Funding $2,500', 'Instant Funding', 'instant-funding', '$2,500', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 129, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-5k', 'Instant Funding $5,000', 'Instant Funding', 'instant-funding', '$5,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 239, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-10k', 'Instant Funding $10,000', 'Instant Funding', 'instant-funding', '$10,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 459, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-20k', 'Instant Funding $20,000', 'Instant Funding', 'instant-funding', '$20,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 899, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-40k', 'Instant Funding $40,000', 'Instant Funding', 'instant-funding', '$40,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 1849, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-80k', 'Instant Funding $80,000', 'Instant Funding', 'instant-funding', '$80,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 3699, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-120k', 'Instant Funding $120,000', 'Instant Funding', 'instant-funding', '$120,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 5499, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. Minimum $25.', 'None. Risk per trade idea capped at 3% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-1250', 'Instant Funding GO $1,250', 'Instant Funding', 'instant-funding', '$1,250', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 67, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-2500', 'Instant Funding GO $2,500', 'Instant Funding', 'instant-funding', '$2,500', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 103, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-5k', 'Instant Funding GO $5,000', 'Instant Funding', 'instant-funding', '$5,000', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 191, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-10k', 'Instant Funding GO $10,000', 'Instant Funding', 'instant-funding', '$10,000', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 367, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-20k', 'Instant Funding GO $20,000', 'Instant Funding', 'instant-funding', '$20,000', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 719, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-40k', 'Instant Funding GO $40,000', 'Instant Funding', 'instant-funding', '$40,000', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 1479, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-go-80k', 'Instant Funding GO $80,000', 'Instant Funding', 'instant-funding', '$80,000', 'Instant funding', 10, 4, null, 'Smart Drawdown (hybrid)', 'Static', 80, 2959, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade.', 'None. Risk per trade idea capped at 2% of starting balance (funded accounts only).', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-5k', 'IF Micro $5,000', 'Instant Funding', 'instant-funding', '$5,000', 'Instant funding', 6, 4, null, 'Static Drawdown', 'Static', 80, 42, null, 'On demand: net profit at least 5% of starting balance and best day within the consistency limit.', 'Best trading day must be 15% or less of total profit (20% with the consistency add-on). Risk per trade idea 1% of starting balance.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-10k', 'IF Micro $10,000', 'Instant Funding', 'instant-funding', '$10,000', 'Instant funding', 6, 4, null, 'Static Drawdown', 'Static', 80, 79, null, 'On demand: net profit at least 5% of starting balance and best day within the consistency limit.', 'Best trading day must be 15% or less of total profit (20% with the consistency add-on). Risk per trade idea 1% of starting balance.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-25k', 'IF Micro $25,000', 'Instant Funding', 'instant-funding', '$25,000', 'Instant funding', 6, 4, null, 'Static Drawdown', 'Static', 80, 169, null, 'On demand: net profit at least 5% of starting balance and best day within the consistency limit.', 'Best trading day must be 15% or less of total profit (20% with the consistency add-on). Risk per trade idea 1% of starting balance.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-50k', 'IF Micro $50,000', 'Instant Funding', 'instant-funding', '$50,000', 'Instant funding', 6, 4, null, 'Static Drawdown', 'Static', 80, 319, null, 'On demand: net profit at least 5% of starting balance and best day within the consistency limit.', 'Best trading day must be 15% or less of total profit (20% with the consistency add-on). Risk per trade idea 1% of starting balance.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-100k', 'IF Micro $100,000', 'Instant Funding', 'instant-funding', '$100,000', 'Instant funding', 6, 4, null, 'Static Drawdown', 'Static', 80, 589, null, 'On demand: net profit at least 5% of starting balance and best day within the consistency limit.', 'Best trading day must be 15% or less of total profit (20% with the consistency add-on). Risk per trade idea 1% of starting balance.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if1-2k', 'IF1 (24-Hour Account) $2,000', 'Instant Funding', 'instant-funding', '$2,000', 'Instant, 24h window', 4, 2, 2, 'Static Drawdown', 'Static', 90, 25, null, 'One payout after the trading window closes, if net profit is at least 2% and the 15% best-trade rule is met.', 'Best trade must be 15% or less of total profit. One open trade at a time. Risk per trade idea 1%.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if1-5k', 'IF1 (24-Hour Account) $5,000', 'Instant Funding', 'instant-funding', '$5,000', 'Instant, 24h window', 4, 2, 2, 'Static Drawdown', 'Static', 90, 38, null, 'One payout after the trading window closes, if net profit is at least 2% and the 15% best-trade rule is met.', 'Best trade must be 15% or less of total profit. One open trade at a time. Risk per trade idea 1%.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if1-10k', 'IF1 (24-Hour Account) $10,000', 'Instant Funding', 'instant-funding', '$10,000', 'Instant, 24h window', 4, 2, 2, 'Static Drawdown', 'Static', 90, 63, null, 'One payout after the trading window closes, if net profit is at least 2% and the 15% best-trade rule is met.', 'Best trade must be 15% or less of total profit. One open trade at a time. Risk per trade idea 1%.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if1-20k', 'IF1 (24-Hour Account) $20,000', 'Instant Funding', 'instant-funding', '$20,000', 'Instant, 24h window', 4, 2, 2, 'Static Drawdown', 'Static', 90, 119, null, 'One payout after the trading window closes, if net profit is at least 2% and the 15% best-trade rule is met.', 'Best trade must be 15% or less of total profit. One open trade at a time. Risk per trade idea 1%.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if1-50k', 'IF1 (24-Hour Account) $50,000', 'Instant Funding', 'instant-funding', '$50,000', 'Instant, 24h window', 4, 2, 2, 'Static Drawdown', 'Static', 90, 289, null, 'One payout after the trading window closes, if net profit is at least 2% and the 15% best-trade rule is met.', 'Best trade must be 15% or less of total profit. One open trade at a time. Risk per trade idea 1%.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if1-100k', 'IF1 (24-Hour Account) $100,000', 'Instant Funding', 'instant-funding', '$100,000', 'Instant, 24h window', 4, 2, 2, 'Static Drawdown', 'Static', 90, 484, null, 'One payout after the trading window closes, if net profit is at least 2% and the 15% best-trade rule is met.', 'Best trade must be 15% or less of total profit. One open trade at a time. Risk per trade idea 1%.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-5k', 'One-Phase Challenge $5,000', 'Instant Funding', 'instant-funding', '$5,000', '1 step', 8, 3, 10, 'Static Drawdown', 'Static', 80, 44, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 40% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-10k', 'One-Phase Challenge $10,000', 'Instant Funding', 'instant-funding', '$10,000', '1 step', 8, 3, 10, 'Static Drawdown', 'Static', 80, 84, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 40% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-25k', 'One-Phase Challenge $25,000', 'Instant Funding', 'instant-funding', '$25,000', '1 step', 8, 3, 10, 'Static Drawdown', 'Static', 80, 179, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 40% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-50k', 'One-Phase Challenge $50,000', 'Instant Funding', 'instant-funding', '$50,000', '1 step', 8, 3, 10, 'Static Drawdown', 'Static', 80, 369, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 40% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-100k', 'One-Phase Challenge $100,000', 'Instant Funding', 'instant-funding', '$100,000', '1 step', 8, 3, 10, 'Static Drawdown', 'Static', 80, 649, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 40% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-micro-10k', 'One-Phase Micro $10,000', 'Instant Funding', 'instant-funding', '$10,000', '1 step', 7, 4, 7, 'Static Drawdown', 'Static', 80, 39, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 15% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-micro-25k', 'One-Phase Micro $25,000', 'Instant Funding', 'instant-funding', '$25,000', '1 step', 7, 4, 7, 'Static Drawdown', 'Static', 80, 64, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 15% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-micro-50k', 'One-Phase Micro $50,000', 'Instant Funding', 'instant-funding', '$50,000', '1 step', 7, 4, 7, 'Static Drawdown', 'Static', 80, 114, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 15% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-micro-100k', 'One-Phase Micro $100,000', 'Instant Funding', 'instant-funding', '$100,000', '1 step', 7, 4, 7, 'Static Drawdown', 'Static', 80, 259, null, 'On demand: net profit at least 1.5% of starting balance or $25, whichever is larger.', 'Best trading day must be 15% or less of total profit. Risk per trade idea: 50% of the starting daily drawdown.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-625', 'Instant Funding Clarity $625', 'Instant Funding', 'instant-funding', '$625', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 49, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-1250', 'Instant Funding Clarity $1,250', 'Instant Funding', 'instant-funding', '$1,250', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 93, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-2500', 'Instant Funding Clarity $2,500', 'Instant Funding', 'instant-funding', '$2,500', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 142, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-5k', 'Instant Funding Clarity $5,000', 'Instant Funding', 'instant-funding', '$5,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 263, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-10k', 'Instant Funding Clarity $10,000', 'Instant Funding', 'instant-funding', '$10,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 505, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-20k', 'Instant Funding Clarity $20,000', 'Instant Funding', 'instant-funding', '$20,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 989, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-40k', 'Instant Funding Clarity $40,000', 'Instant Funding', 'instant-funding', '$40,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 2034, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-80k', 'Instant Funding Clarity $80,000', 'Instant Funding', 'instant-funding', '$80,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 4069, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'instant-funding-clarity-120k', 'Instant Funding Clarity $120,000', 'Instant Funding', 'instant-funding', '$120,000', 'Instant funding', 10, null, null, 'Smart Drawdown (hybrid)', 'Static', 80, 6049, null, 'First withdrawal 14 days after the first trade, then every 7 days after placing a new trade. All trades closed and Smart Drawdown locked in before requesting.', 'None. Account Drawdown circuit breaker at 2.5% of starting balance on floating PnL: a first flag cuts the profit split to 50%, a second breaches the account.', true, false, false, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-clarity-5k', 'IF Micro Clarity $5,000', 'Instant Funding', 'instant-funding', '$5,000', 'Instant funding', 6, 3, null, 'Trailing Drawdown', 'Static', 80, 109, null, 'On demand: net profit at least 3% of starting balance, best day 20% or less, 5 minimum profitable days completed. On $200,000 accounts the first two payouts are capped at $4,000 each.', 'Best trading day must be 20% or less of total profit. 5 minimum profitable days of 0.5% each per payout. Account Drawdown circuit breaker at 1.5% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-clarity-10k', 'IF Micro Clarity $10,000', 'Instant Funding', 'instant-funding', '$10,000', 'Instant funding', 6, 3, null, 'Trailing Drawdown', 'Static', 80, 145, null, 'On demand: net profit at least 3% of starting balance, best day 20% or less, 5 minimum profitable days completed. On $200,000 accounts the first two payouts are capped at $4,000 each.', 'Best trading day must be 20% or less of total profit. 5 minimum profitable days of 0.5% each per payout. Account Drawdown circuit breaker at 1.5% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-clarity-25k', 'IF Micro Clarity $25,000', 'Instant Funding', 'instant-funding', '$25,000', 'Instant funding', 6, 3, null, 'Trailing Drawdown', 'Static', 80, 252, null, 'On demand: net profit at least 3% of starting balance, best day 20% or less, 5 minimum profitable days completed. On $200,000 accounts the first two payouts are capped at $4,000 each.', 'Best trading day must be 20% or less of total profit. 5 minimum profitable days of 0.5% each per payout. Account Drawdown circuit breaker at 1.5% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-clarity-50k', 'IF Micro Clarity $50,000', 'Instant Funding', 'instant-funding', '$50,000', 'Instant funding', 6, 3, null, 'Trailing Drawdown', 'Static', 80, 431, null, 'On demand: net profit at least 3% of starting balance, best day 20% or less, 5 minimum profitable days completed. On $200,000 accounts the first two payouts are capped at $4,000 each.', 'Best trading day must be 20% or less of total profit. 5 minimum profitable days of 0.5% each per payout. Account Drawdown circuit breaker at 1.5% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-clarity-100k', 'IF Micro Clarity $100,000', 'Instant Funding', 'instant-funding', '$100,000', 'Instant funding', 6, 3, null, 'Trailing Drawdown', 'Static', 80, 789, null, 'On demand: net profit at least 3% of starting balance, best day 20% or less, 5 minimum profitable days completed. On $200,000 accounts the first two payouts are capped at $4,000 each.', 'Best trading day must be 20% or less of total profit. 5 minimum profitable days of 0.5% each per payout. Account Drawdown circuit breaker at 1.5% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-micro-clarity-200k', 'IF Micro Clarity $200,000', 'Instant Funding', 'instant-funding', '$200,000', 'Instant funding', 6, 3, null, 'Trailing Drawdown', 'Static', 80, 1505, null, 'On demand: net profit at least 3% of starting balance, best day 20% or less, 5 minimum profitable days completed. On $200,000 accounts the first two payouts are capped at $4,000 each.', 'Best trading day must be 20% or less of total profit. 5 minimum profitable days of 0.5% each per payout. Account Drawdown circuit breaker at 1.5% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-clarity-5k', 'One-Phase Clarity $5,000', 'Instant Funding', 'instant-funding', '$5,000', '1 step', 6, 4, 9, 'Trailing Drawdown', 'Static', 80, 119, null, 'First payout on demand once funded, minimum 1.5% of starting balance, then every 7 days from the first trade.', 'None. Account Drawdown circuit breaker at 2% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-clarity-10k', 'One-Phase Clarity $10,000', 'Instant Funding', 'instant-funding', '$10,000', '1 step', 6, 4, 9, 'Trailing Drawdown', 'Static', 80, 189, null, 'First payout on demand once funded, minimum 1.5% of starting balance, then every 7 days from the first trade.', 'None. Account Drawdown circuit breaker at 2% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-clarity-25k', 'One-Phase Clarity $25,000', 'Instant Funding', 'instant-funding', '$25,000', '1 step', 6, 4, 9, 'Trailing Drawdown', 'Static', 80, 259, null, 'First payout on demand once funded, minimum 1.5% of starting balance, then every 7 days from the first trade.', 'None. Account Drawdown circuit breaker at 2% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-clarity-50k', 'One-Phase Clarity $50,000', 'Instant Funding', 'instant-funding', '$50,000', '1 step', 6, 4, 9, 'Trailing Drawdown', 'Static', 80, 439, null, 'First payout on demand once funded, minimum 1.5% of starting balance, then every 7 days from the first trade.', 'None. Account Drawdown circuit breaker at 2% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'one-phase-clarity-100k', 'One-Phase Clarity $100,000', 'Instant Funding', 'instant-funding', '$100,000', '1 step', 6, 4, 9, 'Trailing Drawdown', 'Static', 80, 799, null, 'First payout on demand once funded, minimum 1.5% of starting balance, then every 7 days from the first trade.', 'None. Account Drawdown circuit breaker at 2% of starting balance on floating PnL.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-evolve-10k', 'IF Evolve (Futures Style) $10,000', 'Instant Funding', 'instant-funding', '$10,000', '1 step, futures style', 4, null, 6, 'End-of-Day trailing drawdown', 'Static', 80, 49, null, 'On demand once funded. Minimum withdrawal $250, capped at 50% of account profit and $2,000 per request, maximum 5 payouts per account.', 'Best trading day must be 40% or less of total profit, on the challenge and once funded. 5 minimum profitable days of 0.25% each.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-evolve-25k', 'IF Evolve (Futures Style) $25,000', 'Instant Funding', 'instant-funding', '$25,000', '1 step, futures style', 4, null, 6, 'End-of-Day trailing drawdown', 'Static', 80, 69, null, 'On demand once funded. Minimum withdrawal $250, capped at 50% of account profit and $2,000 per request, maximum 5 payouts per account.', 'Best trading day must be 40% or less of total profit, on the challenge and once funded. 5 minimum profitable days of 0.25% each.', true, false, true, 'one-time', 'percent'),
  (gen_random_uuid(), 'if-evolve-50k', 'IF Evolve (Futures Style) $50,000', 'Instant Funding', 'instant-funding', '$50,000', '1 step, futures style', 4, null, 6, 'End-of-Day trailing drawdown', 'Static', 80, 99, null, 'On demand once funded. Minimum withdrawal $250, capped at 50% of account profit and $2,000 per request, maximum 5 payouts per account.', 'Best trading day must be 40% or less of total profit, on the challenge and once funded. 5 minimum profitable days of 0.25% each.', true, false, true, 'one-time', 'percent');

-- Controle avant de valider : doit renvoyer 59.
select count(*) as lignes_inserees from prop_firm_challenges where firm_slug = 'instant-funding';

commit;


-- -----------------------------------------------------------------------------
-- ETAPE 3 — Verification
-- -----------------------------------------------------------------------------
select name, account_size, price, max_drawdown, max_daily_loss,
       phase1_profit_target, profit_split, drawdown_type
from prop_firm_challenges
where firm_slug = 'instant-funding'
order by price;
