-- =============================================================================
-- THE5ERS — PROGRAMMES v2 (marches, familles, variantes)
-- =============================================================================
-- Prerequis : RUN-program-schema.sql PUIS RUN-program-schema-v2.sql.
-- Source : audit officiel du 2026-09-04.
--
-- Ce fichier n efface et ne reinsere QUE les lignes de cette firme.
-- prop_firm_challenges n est pas touchee : l ancien configurateur reste
-- disponible en repli tant que ces programmes ne couvrent pas tout.
-- =============================================================================


-- 1. Table rase pour cette firme
delete from firm_program_plans where program_id in (select id from firm_programs where firm_slug = 'the5ers');
delete from firm_programs where firm_slug = 'the5ers';
delete from firm_promotions where firm_slug = 'the5ers';
delete from firm_rules where firm_slug = 'the5ers';


-- 2. 8 programmes
-- Dont 5 sans aucun plan : High Stakes, Bootcamp, Pro Growth, Hyper Growth, Stock Trading.
-- Un programme sans plan s affiche comme « verification en cours ». C est
-- voulu : recopier les regles d un produit voisin serait pire que le vide.
insert into firm_programs (firm_slug, slug, name, market, program_family, status,
  kind, evaluation_steps, summary, sort_order, max_funded_accounts, max_funded_note,
  source_url, verified_at) values
  ('the5ers', 't5-summer-cfd-1-step', 'Summer Plan CFD 1-Step', 'cfd', 'Summer Plan', 'promotional', 'evaluation', 1, 'A promotional one-phase plan on a $100K account, with a 50% daily consistency rule and a 75% split.', 1, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-summer-cfd-2-step', 'Summer Plan CFD 2-Step', 'cfd', 'Summer Plan', 'promotional', 'evaluation', 2, 'Four promotional variants: two target sets, 8/5 and 10/5, on $100K and $200K. The cheaper variant asks for the higher first target.', 2, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-summer-futures', 'Summer Plan Futures', 'futures', 'Summer Plan', 'promotional', 'evaluation', 1, 'A futures plan with an end-of-day maximum loss, contract limits per size and tighter overnight limits. Passing in a single day is possible.', 3, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-high-stakes', 'High Stakes', 'cfd', 'Classic', 'unverified', 'evaluation', null, 'Listed as a classic programme. Its availability at checkout has not been reverified since the Summer Plan launched, so no price or rule is published here.', 4, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-bootcamp', 'Bootcamp', 'cfd', 'Classic', 'unverified', 'evaluation', null, 'Listed as a classic programme. Its availability at checkout has not been reverified since the Summer Plan launched, so no price or rule is published here.', 5, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-pro-growth', 'Pro Growth', 'cfd', 'Classic', 'unverified', 'evaluation', null, 'Listed as a classic programme. Its availability at checkout has not been reverified since the Summer Plan launched, so no price or rule is published here.', 6, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-hyper-growth', 'Hyper Growth', 'cfd', 'Classic', 'unverified', 'evaluation', null, 'Listed as a classic programme. Its availability at checkout has not been reverified since the Summer Plan launched, so no price or rule is published here.', 7, null, null, 'https://the5ers.com/', timestamptz '2026-09-04'),
  ('the5ers', 't5-stock-trading', 'Stock Trading', 'stocks', 'Classic', 'unverified', 'evaluation', null, 'Listed as a classic programme. Its availability at checkout has not been reverified since the Summer Plan launched, so no price or rule is published here.', 8, null, null, 'https://the5ers.com/', timestamptz '2026-09-04');


-- 3. 22 plans — une ligne par programme x variante x phase x taille
insert into firm_program_plans (program_id, phase, account_size, variant_key, variant_label, account_type, target_variant, currency, platform, regular_price, post_pass_fee, profit_target, maximum_loss_limit, daily_loss_limit, drawdown_type, buffer, buffer_status, max_contracts, contract_scaling, minimum_trading_days, minimum_profitable_days, consistency_rule, best_day_rule, profit_split, payout_cap, minimum_payout, days_between_payouts, reset_fee, activation_fee, leverage, time_limit, news_trading_status, overnight_rule, weekend_rule, payout_eligible, scaling_note, refund_note, source_url, verified_at, confidence, editorial_note) values
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-1-step'), 'evaluation', 100000, null, null, null, null, 'USD', null, 249, null, 0.1, 0.06, 0.03, null, null, 'not_stated', null, null, null, null, 0.5, null, null, null, null, null, null, null, '1:100', 'Unlimited', null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', 'Consistency is measured per day on this plan.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-1-step'), 'sim_funded', 100000, null, null, null, null, 'USD', null, null, null, null, 0.06, 0.03, null, null, 'not_stated', null, null, null, null, null, null, 0.75, 2000, 250, null, null, null, '1:100', null, null, null, null, null, null, 'The fee is refunded at the third payout. A 10% bonus is advertised.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation', 100000, '8-5', '8% / 5%', null, '8/5', 'USD', null, 179, null, 0.08, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, '1:100', 'Unlimited', null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation_2', 100000, '8-5', '8% / 5%', null, '8/5', 'USD', null, null, null, 0.05, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'sim_funded', 100000, '8-5', '8% / 5%', null, '8/5', 'USD', null, null, null, null, null, null, null, null, 'not_stated', null, null, null, null, 0.5, null, 0.8, 2000, 250, null, null, null, '1:100', null, null, null, null, null, null, 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation', 100000, '10-5', '10% / 5%', null, '10/5', 'USD', null, 149, null, 0.1, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, '1:100', 'Unlimited', null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation_2', 100000, '10-5', '10% / 5%', null, '10/5', 'USD', null, null, null, 0.05, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'sim_funded', 100000, '10-5', '10% / 5%', null, '10/5', 'USD', null, null, null, null, null, null, null, null, 'not_stated', null, null, null, null, 0.5, null, 0.8, 2000, 250, null, null, null, '1:100', null, null, null, null, null, null, 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation', 200000, '8-5', '8% / 5%', null, '8/5', 'USD', null, 279, null, 0.08, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, '1:100', 'Unlimited', null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation_2', 200000, '8-5', '8% / 5%', null, '8/5', 'USD', null, null, null, 0.05, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'sim_funded', 200000, '8-5', '8% / 5%', null, '8/5', 'USD', null, null, null, null, null, null, null, null, 'not_stated', null, null, null, null, 0.5, null, 0.8, 3000, 250, null, null, null, '1:100', null, null, null, null, null, null, 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'needs_confirmation', 'The source site displays 100% as the funded scaling target on the $200K variants. That looks like a rendering fault and is not imported as a rule.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation', 200000, '10-5', '10% / 5%', null, '10/5', 'USD', null, 249, null, 0.1, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, '1:100', 'Unlimited', null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'evaluation_2', 200000, '10-5', '10% / 5%', null, '10/5', 'USD', null, null, null, 0.05, 0.1, 0.03, null, null, 'not_stated', null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-cfd-2-step'), 'sim_funded', 200000, '10-5', '10% / 5%', null, '10/5', 'USD', null, null, null, null, null, null, null, null, 'not_stated', null, null, null, null, 0.5, null, 0.8, 3000, 250, null, null, null, '1:100', null, null, null, null, null, null, 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'needs_confirmation', 'Same rendering anomaly on the funded scaling target for the $200K variants.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'evaluation', 25000, null, null, null, null, 'USD', null, 69, null, 0.06, 0.04, null, 'End of day', null, 'not_stated', 2, null, null, null, null, null, null, null, null, null, null, 0, null, 'Unlimited', null, null, null, null, 'Scaling up to $500,000.', 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', 'Contract limits: 2 mini / 20 micro. Overnight: 1 mini / 10 micro.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'sim_funded', 25000, null, null, null, null, 'USD', null, null, null, 0.04, 0.04, null, 'End of day', null, 'not_stated', 2, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1 mini / 10 micro overnight.', null, null, 'Scaling up to $500,000.', null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'evaluation', 50000, null, null, null, null, 'USD', null, 120, null, 0.06, 0.04, null, 'End of day', null, 'not_stated', 4, null, null, null, null, null, null, null, null, null, null, 0, null, 'Unlimited', null, null, null, null, 'Scaling up to $500,000.', 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', 'Contract limits: 4 mini / 40 micro. Overnight: 1 mini / 10 micro.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'sim_funded', 50000, null, null, null, null, 'USD', null, null, null, 0.04, 0.04, null, 'End of day', null, 'not_stated', 4, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1 mini / 10 micro overnight.', null, null, 'Scaling up to $500,000.', null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'evaluation', 100000, null, null, null, null, 'USD', null, 189, null, 0.06, 0.04, null, 'End of day', null, 'not_stated', 8, null, null, null, null, null, null, null, null, null, null, 0, null, 'Unlimited', null, null, null, null, 'Scaling up to $500,000.', 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', 'Contract limits: 8 mini / 80 micro. Overnight: 2 mini / 20 micro.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'sim_funded', 100000, null, null, null, null, 'USD', null, null, null, 0.04, 0.04, null, 'End of day', null, 'not_stated', 8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2 mini / 20 micro overnight.', null, null, 'Scaling up to $500,000.', null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'evaluation', 150000, null, null, null, null, 'USD', null, 219, null, 0.06, 0.04, null, 'End of day', null, 'not_stated', 12, null, null, null, null, null, null, null, null, null, null, 0, null, 'Unlimited', null, null, null, null, 'Scaling up to $500,000.', 'The fee is refunded at the third payout.', 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', 'Contract limits: 12 mini / 120 micro. Overnight: 3 mini / 30 micro.'),
  ((select id from firm_programs where firm_slug = 'the5ers' and slug = 't5-summer-futures'), 'sim_funded', 150000, null, null, null, null, 'USD', null, null, null, 0.04, 0.04, null, 'End of day', null, 'not_stated', 12, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3 mini / 30 micro overnight.', null, null, 'Scaling up to $500,000.', null, 'https://the5ers.com/', timestamptz '2026-09-04', 'verified', null);


-- 5. 6 regles. program_slug null = regle de toute la firme.
--    Renseigne = regle propre a ce programme, jamais affichee sous un autre.
insert into firm_rules (firm_slug, program_slug, scope, title, detail, severity,
  confidence, source_url, verified_at, sort_order) values
  ('the5ers', null, 'promotion', 'Summer Plan expiry', 'No expiry date is published for the Summer Plan. It is a promotional catalogue, not a permanent one.', 'informational', 'needs_confirmation', 'https://the5ers.com/', timestamptz '2026-09-04', 1),
  ('the5ers', null, 'catalogue', 'Classic programmes', 'High Stakes, Bootcamp, Pro Growth, Hyper Growth and Stock Trading are listed without prices or rules until their availability at checkout is reverified.', 'informational', 'needs_confirmation', 'https://the5ers.com/', timestamptz '2026-09-04', 2),
  ('the5ers', 't5-summer-futures', 'consistency', 'Consistency per position, 40%', 'The futures plan advertises a 40% consistency measured per position. That is not the usual best-day rule, and its exact definition has not been obtained.', 'eligibility_condition', 'needs_confirmation', 'https://the5ers.com/', timestamptz '2026-09-04', 3),
  ('the5ers', 't5-summer-cfd-2-step', 'anomaly', 'Funded scaling target shown as 100%', 'The source site displays 100% as the funded scaling target on the $200K variants. Treated as an unresolved rendering anomaly, not as a rule.', 'informational', 'needs_confirmation', 'https://the5ers.com/', timestamptz '2026-09-04', 4),
  ('the5ers', null, 'promotion', 'Code GDSWCVRTE7', 'A code is present in our database with unknown origin, scope and validity. It is not published until confirmed to be a discount code, a referral code, or both.', 'informational', 'needs_confirmation', 'https://the5ers.com/', timestamptz '2026-09-04', 5),
  ('the5ers', null, 'account', 'Account limits', 'Summer CFD 1-Step allows a maximum of two active accounts. Summer CFD 2-Step allows two $100K accounts or one $200K account.', 'restriction', 'verified', 'https://the5ers.com/', timestamptz '2026-09-04', 6);


-- 6. CONTROLE
-- Attendu : 8 programmes, 22 plans, 0 promo, 6 regles.
select p.name, p.market, p.status, pl.variant_label, pl.phase, pl.account_size,
       pl.regular_price, pl.currency, pl.profit_target, pl.daily_loss_limit,
       pl.best_day_rule, pl.consistency_rule, pl.profit_split
from firm_programs p left join firm_program_plans pl on pl.program_id = p.id
where p.firm_slug = 'the5ers'
order by p.sort_order, pl.variant_key nulls first, pl.account_size, pl.phase;
