-- =============================================================================
-- E8-MARKETS — PROGRAMMES, PRIX, PROMOTIONS ET REGLES
-- =============================================================================
-- Prerequis : database/RUN-program-schema.sql doit avoir ete passe une fois.
--
-- Source : classeur du 2026-09-04. Les classeurs tassent leurs valeurs vers la
-- gauche quand un champ est vide ; les valeurs ont donc ete recopiees apres
-- controle semantique, et tout champ au placement ambigu porte
-- confidence = 'needs_confirmation' plutot qu une affirmation.
--
-- Idempotent : les lignes de cette firme sont effacees puis reinserees.
-- Aucune autre firme n est touchee.
-- =============================================================================


-- 1. Table rase pour cette firme uniquement
delete from firm_program_plans where program_id in (select id from firm_programs where firm_slug = 'e8-markets');
delete from firm_programs where firm_slug = 'e8-markets';
delete from firm_promotions where firm_slug = 'e8-markets';
delete from firm_program_bundles where firm_slug = 'e8-markets';
delete from firm_platforms where firm_slug = 'e8-markets';
delete from firm_rules where firm_slug = 'e8-markets';
delete from firm_live_tiers where firm_slug = 'e8-markets';


-- 2. Les 5 programmes
insert into firm_programs (firm_slug, slug, name, kind, evaluation_steps, summary, sort_order, max_funded_accounts, max_funded_note, source_url, verified_at) values
  ('e8-markets', 'e8-one', 'E8 One', 'evaluation', 1, 'Single phase on Forex and perpetuals. Dynamic drawdown that becomes static at the starting balance, and parameters you choose at checkout.', 1, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04'),
  ('e8-markets', 'e8-pro', 'E8 Pro', 'evaluation', 1, 'Single phase with a static drawdown that moves to the initial balance after the first payout. Daily payouts use a 50/50 paid/retained buffer.', 2, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04'),
  ('e8-markets', 'e8-signature', 'E8 Signature', 'evaluation', 1, 'Single phase across Forex, perpetuals and futures. Its daily rule is a Daily Pause — a soft stop, not a breach.', 3, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04'),
  ('e8-markets', 'e8-zero-starter', 'E8 Zero Starter', 'evaluation', 1, 'Futures only. Best Day rule of 40% during the challenge, none in performance. Payouts are capped and limited to five per account.', 4, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04'),
  ('e8-markets', 'e8-zero-max', 'E8 Zero Max', 'evaluation', 1, 'The larger Zero tier. Same futures-only rules, higher entry price.', 5, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04');


-- 3. Les 26 plans, une ligne par programme x phase x taille
insert into firm_program_plans (program_id, phase, account_size, regular_price,
  profit_target, maximum_loss_limit, daily_loss_limit, drawdown_type, buffer,
  buffer_status, max_contracts, contract_scaling, minimum_trading_days,
  consistency_rule, profit_split, payout_cap, minimum_payout, days_between_payouts,
  reset_fee, activation_fee, news_trading_status, news_trading_note,
  scalping_status, scalping_note, source_url, verified_at, confidence, editorial_note) values
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 5000, 48, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 10000, 88, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 25000, 188, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 50000, 288, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 100000, 488, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 200000, 798, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 400000, 1598, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-one'), 'evaluation', 500000, 1998, 0.09, 0.06, 0.04, 'Dynamic, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', 'Allowed during the challenge, not allowed in the performance stage.', null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Preset values. Drawdown 4-14%, daily 3-9.2%, target 6-21% and payout share 80-100% are chosen at checkout, and the price changes with them. The daily figure sat in a column meant for a second phase: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 5000, 32, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 10000, 68, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 25000, 148, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 50000, 228, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 100000, 488, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 200000, 998, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 400000, 2098, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-pro'), 'evaluation', 500000, 2598, 0.08, 0.08, 0.025, 'Static, moves to the initial balance after the first payout', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 'needs_confirmation', 'Daily payout requires at least 1% profit and pays 50% while retaining 50% as a buffer. The 2.5% daily figure sat in a second-phase column on a single-phase product: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-signature'), 'evaluation', 25000, 110, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Market-specific preset; the checkout figures should be reverified. The 80% is the preset payout share, confirmed by the payouts table — the workbook had placed it in a profit-target column.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-signature'), 'evaluation', 50000, 150, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Market-specific preset; the checkout figures should be reverified. The 80% is the preset payout share, confirmed by the payouts table — the workbook had placed it in a profit-target column.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-signature'), 'evaluation', 100000, 260, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Market-specific preset; the checkout figures should be reverified. The 80% is the preset payout share, confirmed by the payouts table — the workbook had placed it in a profit-target column.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-signature'), 'evaluation', 150000, 390, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Market-specific preset; the checkout figures should be reverified. The 80% is the preset payout share, confirmed by the payouts table — the workbook had placed it in a profit-target column.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-zero-starter'), 'evaluation', 50000, 178, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Help Center table values. The 80% share sat in a profit-target column and is not listed in the payouts table for Zero: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-zero-starter'), 'evaluation', 100000, 278, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Help Center table values. The 80% share sat in a profit-target column and is not listed in the payouts table for Zero: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-zero-starter'), 'evaluation', 200000, 558, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Help Center table values. The 80% share sat in a profit-target column and is not listed in the payouts table for Zero: to be confirmed.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-zero-max'), 'evaluation', 50000, 328, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Help Center table values. Same caveat on the 80% share as E8 Zero Starter.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-zero-max'), 'evaluation', 100000, 588, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Help Center table values. Same caveat on the 80% share as E8 Zero Starter.'),
  ((select id from firm_programs where firm_slug = 'e8-markets' and slug = 'e8-zero-max'), 'evaluation', 200000, 1088, null, null, null, 'End-of-day dynamic on closed profits, becomes static at the starting balance', null, 'not_stated', null, null, null, null, 0.8, null, null, null, null, null, 'allowed', null, null, null, 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 'needs_confirmation', 'Help Center table values. Same caveat on the 80% share as E8 Zero Starter.');


-- 4. 8 promotion(s), datees et jamais qualifiees de permanentes
insert into firm_promotions (firm_slug, program_slug, account_size, code, label,
  discount_type, discount_value, starts_at, expires_at, verified_at, source_url,
  status, is_public, editorial_note) values
  ('e8-markets', 'e8-one', 5000, null, 'Public homepage price', 'amount', 26, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 10000, null, 'Public homepage price', 'amount', 49, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 25000, null, 'Public homepage price', 'amount', 104, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 50000, null, 'Public homepage price', 'amount', 160, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 100000, null, 'Public homepage price', 'amount', 272, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 200000, null, 'Public homepage price', 'amount', 445, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 400000, null, 'Public homepage price', 'amount', 891, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.'),
  ('e8-markets', 'e8-one', 500000, null, 'Public homepage price', 'amount', 1114, null, null, timestamptz '2026-09-04', 'https://e8markets.com/', 'active', true, 'The homepage shows a lower price than the Help Center base table. Stored as a dated public offer, not as the permanent price.');


-- 5. Plateformes
insert into firm_platforms (firm_slug, name, configurator_status, checkout_surcharge, note, sort_order) values
  ('e8-markets', 'MetaTrader 5', 'selectable', 'not_displayed', null, 1),
  ('e8-markets', 'TradeLocker', 'selectable', 'not_displayed', null, 2),
  ('e8-markets', 'cTrader', 'selectable', 'not_displayed', null, 3),
  ('e8-markets', 'MatchTrader', 'selectable', 'not_displayed', null, 4),
  ('e8-markets', 'E8 Terminal', 'selectable', 'not_displayed', null, 5),
  ('e8-markets', 'Tradovate', 'selectable', 'not_displayed', 'Futures availability to verify', 6);


-- 6. 21 regles, avec leur niveau de gravite
insert into firm_rules (firm_slug, scope, title, detail, severity, confidence, source_url, verified_at, sort_order) values
  ('e8-markets', 'structure', 'Phases', 'Every current product is single phase.', 'allowed', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 1),
  ('e8-markets', 'drawdown', 'E8 One drawdown', 'Dynamic drawdown that becomes static once it reaches the starting balance.', 'restriction', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 2),
  ('e8-markets', 'drawdown', 'E8 Pro drawdown', 'Static drawdown, moved to the initial balance after the first payout.', 'restriction', 'verified', 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 3),
  ('e8-markets', 'drawdown', 'E8 Signature and Zero drawdown', 'End-of-day dynamic, based on closed profits, becoming static at the starting balance.', 'restriction', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 4),
  ('e8-markets', 'daily', 'E8 Signature daily rule', 'A Daily Pause: trading stops for the day. It is a soft breach, not an account closure.', 'restriction', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 5),
  ('e8-markets', 'consistency', 'E8 One Best Day', 'No consistency rule during the challenge. 40% Best Day rule in the performance stage.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 6),
  ('e8-markets', 'consistency', 'E8 Signature Best Day', '35% Best Day rule in the performance stage.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 7),
  ('e8-markets', 'consistency', 'E8 Zero Best Day', '40% Best Day rule during the challenge, none in the performance stage.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 8),
  ('e8-markets', 'news', 'E8 One news trading', 'Allowed during the challenge, not allowed in the performance stage.', 'restriction', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 9),
  ('e8-markets', 'news', 'News trading on Pro, Signature and Zero', 'Allowed.', 'allowed', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 10),
  ('e8-markets', 'session', 'Weekend and overnight on One and Pro', 'Allowed.', 'allowed', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 11),
  ('e8-markets', 'session', 'Weekend and overnight on Signature and Zero', 'Not allowed.', 'hard_breach', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 12),
  ('e8-markets', 'conduct', 'Expert advisers on E8 Zero', 'Not allowed.', 'hard_breach', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 13),
  ('e8-markets', 'conduct', 'Trade copier', 'Allowed on every product.', 'allowed', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 14),
  ('e8-markets', 'payout', 'Minimum payout', '$100 net minimum. The gross profit required depends on the payout share you chose.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/15272556-everything-about-payouts-when-how-how-fast', timestamptz '2026-09-04', 15),
  ('e8-markets', 'payout', 'Providers and KYC', 'Rise or WorkMarket only, and the provider requires its own KYC. No direct unsupported method.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/15272556-everything-about-payouts-when-how-how-fast', timestamptz '2026-09-04', 16),
  ('e8-markets', 'payout', 'Processing time', 'Median 11 hours to approval and 24 hours to the provider between January and May 2026, and it may take up to 5 business days. Weekends are not processed. Firm statistic.', 'payout_condition', 'needs_confirmation', 'https://help.e8markets.com/en/articles/15272556-everything-about-payouts-when-how-how-fast', timestamptz '2026-09-04', 17),
  ('e8-markets', 'payout', 'E8 Pro daily payout', 'Requires at least 1% profit. Half is paid, half is retained as a buffer.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/13653464-payout-request-from-e8-pro-forex-and-e8-pro-crypto', timestamptz '2026-09-04', 18),
  ('e8-markets', 'payout', 'E8 Zero payouts', '$100 minimum, capped, and a maximum of five payouts per account.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 19),
  ('e8-markets', 'payout', 'Payout share on One and Pro', '80%, 90% or 100%, selected at checkout. The price changes with it.', 'payout_condition', 'verified', 'https://help.e8markets.com/en/articles/8880316-what-is-the-custom-account', timestamptz '2026-09-04', 20),
  ('e8-markets', 'legal', 'Simulated trading', 'Amounts shown are rewards for simulated performance, paid in real money. Eligibility and provider KYC still apply.', 'restriction', 'verified', 'https://help.e8markets.com/en/articles/13106558-all-product-overviews-e8-one-vs-e8-zero-vs-e8-pro-vs-e8-signature', timestamptz '2026-09-04', 21);


-- 7. CONTROLE
-- Attendu : 5 programmes, 26 plans, 8 promotion(s), 21 regles.
select p.name, pl.phase, pl.account_size, pl.regular_price, pl.profit_target,
       pl.maximum_loss_limit, pl.daily_loss_limit, pl.profit_split, pl.confidence
from firm_program_plans pl join firm_programs p on p.id = pl.program_id
where p.firm_slug = 'e8-markets'
order by p.sort_order, pl.account_size;
