-- =============================================================================
-- FTMO — PROGRAMMES v2 (marches, familles, variantes)
-- =============================================================================
-- Prerequis : RUN-program-schema.sql PUIS RUN-program-schema-v2.sql.
-- Source : audit officiel du 2026-09-04.
--
-- Ce fichier n efface et ne reinsere QUE les lignes de cette firme.
-- prop_firm_challenges n est pas touchee : l ancien configurateur reste
-- disponible en repli tant que ces programmes ne couvrent pas tout.
-- =============================================================================


-- 1. Table rase pour cette firme
delete from firm_program_plans where program_id in (select id from firm_programs where firm_slug = 'ftmo');
delete from firm_programs where firm_slug = 'ftmo';
delete from firm_promotions where firm_slug = 'ftmo';
delete from firm_rules where firm_slug = 'ftmo';


-- 2. 3 programmes
-- Dont 1 sans aucun plan : FTMO Futures (Beta).
-- Un programme sans plan s affiche comme « verification en cours ». C est
-- voulu : recopier les regles d un produit voisin serait pire que le vide.
insert into firm_programs (firm_slug, slug, name, market, program_family, status,
  kind, evaluation_steps, summary, sort_order, max_funded_accounts, max_funded_note,
  source_url, verified_at) values
  ('ftmo', 'ftmo-cfd-1-step', 'FTMO Challenge 1-Step', 'cfd', 'CFD', 'active', 'evaluation', 1, 'One phase, a 10% target and the highest split of the range. In exchange, a 3% daily loss, a trailing drawdown and a Best Day Rule.', 1, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04'),
  ('ftmo', 'ftmo-cfd-2-step', 'FTMO Challenge 2-Step', 'cfd', 'CFD', 'active', 'evaluation', 2, 'Two phases, 10% then 5%, with a wider 5% daily loss and a static drawdown. The only route with a fee refund and the Scaling Plan.', 2, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04'),
  ('ftmo', 'ftmo-futures-beta', 'FTMO Futures (Beta)', 'futures', 'Futures', 'beta', 'evaluation', null, 'A separate futures product, in beta. Its catalogue and rules are not yet verified, and no CFD rule applies to it.', 3, null, null, 'https://ftmo.com/en/futures/', timestamptz '2026-09-04');


-- 3. 37 plans — une ligne par programme x variante x phase x taille
insert into firm_program_plans (program_id, phase, account_size, variant_key, variant_label, account_type, target_variant, currency, platform, regular_price, post_pass_fee, profit_target, maximum_loss_limit, daily_loss_limit, drawdown_type, buffer, buffer_status, max_contracts, contract_scaling, minimum_trading_days, minimum_profitable_days, consistency_rule, best_day_rule, profit_split, payout_cap, minimum_payout, days_between_payouts, reset_fee, activation_fee, leverage, time_limit, news_trading_status, overnight_rule, weekend_rule, payout_eligible, scaling_note, refund_note, source_url, verified_at, confidence, editorial_note) values
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'evaluation', 10000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 79, null, 0.1, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, 0.5, 0.9, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, 'The Scaling Plan does not apply to the 1-Step.', 'No refund is advertised on the 1-Step.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'evaluation', 25000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 199, null, 0.1, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, 0.5, 0.9, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, 'The Scaling Plan does not apply to the 1-Step.', 'No refund is advertised on the 1-Step.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'evaluation', 50000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 319, null, 0.1, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, 0.5, 0.9, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, 'The Scaling Plan does not apply to the 1-Step.', 'No refund is advertised on the 1-Step.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'evaluation', 100000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 499, null, 0.1, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, 0.5, 0.9, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, 'The Scaling Plan does not apply to the 1-Step.', 'No refund is advertised on the 1-Step.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'evaluation', 200000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 999, null, 0.1, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, 0.5, 0.9, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, 'The Scaling Plan does not apply to the 1-Step.', 'No refund is advertised on the 1-Step.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'sim_funded', 10000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, null, 0.9, null, null, null, null, null, null, null, null, null, null, null, 'The Scaling Plan does not apply to the 1-Step.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'sim_funded', 25000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, null, 0.9, null, null, null, null, null, null, null, null, null, null, null, 'The Scaling Plan does not apply to the 1-Step.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'sim_funded', 50000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, null, 0.9, null, null, null, null, null, null, null, null, null, null, null, 'The Scaling Plan does not apply to the 1-Step.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'sim_funded', 100000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, null, 0.9, null, null, null, null, null, null, null, null, null, null, null, 'The Scaling Plan does not apply to the 1-Step.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-1-step'), 'sim_funded', 200000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.03, 'End-of-day trailing', null, 'not_stated', null, null, null, null, null, null, 0.9, null, null, null, null, null, null, null, null, null, null, null, 'The Scaling Plan does not apply to the 1-Step.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 10000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 89, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 25000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 250, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 50000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 345, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 100000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 540, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 200000, 'standard', 'Standard', 'Standard', null, 'EUR', null, 1080, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', null, null, null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 10000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 25000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 50000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 100000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 200000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 10000, 'swing', 'Swing', 'Swing', null, 'EUR', null, 99, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', 'Allowed, including on the funded account.', 'Allowed, including on the funded account.', null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 25000, 'swing', 'Swing', 'Swing', null, 'EUR', null, 279, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', 'Allowed, including on the funded account.', 'Allowed, including on the funded account.', null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 50000, 'swing', 'Swing', 'Swing', null, 'EUR', null, 379, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', 'Allowed, including on the funded account.', 'Allowed, including on the funded account.', null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation', 100000, 'swing', 'Swing', 'Swing', null, 'EUR', null, 599, null, 0.1, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, 0.8, null, null, null, null, null, null, 'Unlimited', 'allowed', 'Allowed, including on the funded account.', 'Allowed, including on the funded account.', null, '+25% every four active months, up to $2,000,000 combined.', '100% of the fee is refunded, subject to conditions.', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 10000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 25000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 50000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'evaluation_2', 100000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, 0.05, 0.1, 0.05, 'Static', null, 'not_stated', null, null, 4, null, null, null, null, null, null, null, null, null, null, 'Unlimited', null, null, null, null, null, null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 10000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, null, null, null, '+25% every four active months, up to $2,000,000 combined. Requires 10% net simulated profit, two processed rewards and a positive balance at scale-up.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 25000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, null, null, null, '+25% every four active months, up to $2,000,000 combined. Requires 10% net simulated profit, two processed rewards and a positive balance at scale-up.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 50000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, null, null, null, '+25% every four active months, up to $2,000,000 combined. Requires 10% net simulated profit, two processed rewards and a positive balance at scale-up.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 100000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, null, null, null, '+25% every four active months, up to $2,000,000 combined. Requires 10% net simulated profit, two processed rewards and a positive balance at scale-up.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 200000, 'standard', 'Standard', 'Standard', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, null, null, null, '+25% every four active months, up to $2,000,000 combined. Requires 10% net simulated profit, two processed rewards and a positive balance at scale-up.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 10000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, 'Allowed.', 'Allowed.', null, '+25% every four active months, up to $2,000,000 combined.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 25000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, 'Allowed.', 'Allowed.', null, '+25% every four active months, up to $2,000,000 combined.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 50000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, 'Allowed.', 'Allowed.', null, '+25% every four active months, up to $2,000,000 combined.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null),
  ((select id from firm_programs where firm_slug = 'ftmo' and slug = 'ftmo-cfd-2-step'), 'sim_funded', 100000, 'swing', 'Swing', 'Swing', null, 'EUR', null, null, null, null, 0.1, 0.05, 'Static', null, 'not_stated', null, null, null, null, null, null, 0.8, null, null, null, null, null, null, null, null, 'Allowed.', 'Allowed.', null, '+25% every four active months, up to $2,000,000 combined.', null, 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 'verified', null);


-- 4. 1 promotion(s), limitees a leurs variantes eligibles
insert into firm_promotions (firm_slug, program_slug, account_size, code, label,
  discount_type, discount_value, starts_at, expires_at, verified_at, source_url,
  status, is_public, eligible_markets, eligible_variants, stacking_rule,
  checkout_verified, affiliate_exclusive, editorial_note) values
  ('ftmo', 'ftmo-cfd-1-step', 100000, null, 'Public offer', 'percent', 0.2, null, null, timestamptz '2026-09-04', 'https://ftmo.com/fr/', 'active', true, '{"cfd"}'::text[], '{"standard"}'::text[], 'Not documented; assume no stacking.', false, false, 'Observed on the 1-Step $100K only. Not extended to other products without confirmation. No expiry published.');


-- 5. 9 regles. program_slug null = regle de toute la firme.
--    Renseigne = regle propre a ce programme, jamais affichee sous un autre.
insert into firm_rules (firm_slug, program_slug, scope, title, detail, severity,
  confidence, source_url, verified_at, sort_order) values
  ('ftmo', 'ftmo-cfd-1-step', 'consistency', 'Best Day Rule', 'Your best day must stay under 50% of the profit from winning days. Going over does not fail the evaluation: you keep trading until you are back under.', 'eligibility_condition', 'verified', 'https://ftmo.com/fr/trading-objectives/', timestamptz '2026-09-04', 1),
  ('ftmo', 'ftmo-cfd-1-step', 'cost', 'No refund', 'FTMO advertises no fee refund on the 1-Step. The 2-Step refund conditions do not apply here.', 'informational', 'verified', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 2),
  ('ftmo', 'ftmo-cfd-1-step', 'scaling', 'No Scaling Plan', 'The Scaling Plan is a 2-Step feature. It does not apply to the 1-Step.', 'informational', 'verified', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 3),
  ('ftmo', 'ftmo-cfd-2-step', 'consistency', 'No consistency rule', 'The 2-Step has no Best Day Rule. That rule belongs to the 1-Step.', 'allowed', 'verified', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 4),
  ('ftmo', 'ftmo-cfd-2-step', 'cost', 'Fee refund', '100% of the challenge fee is refunded, subject to conditions.', 'eligibility_condition', 'verified', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 5),
  ('ftmo', 'ftmo-cfd-2-step', 'scaling', 'Scaling Plan', '+25% every four active months, up to $2,000,000 combined. Requires 10% net simulated profit, two processed rewards and a positive balance at scale-up.', 'eligibility_condition', 'verified', 'https://ftmo.com/fr/recompense-croissante-et-plan-de-scaling/', timestamptz '2026-09-04', 6),
  ('ftmo', null, 'structure', 'No time limit', 'Neither route has a deadline to pass.', 'allowed', 'verified', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 7),
  ('ftmo', null, 'pricing', 'A second price seen on the 100K', 'A value of €439 was also visible on the 2-Step $100K alongside €540. Its scope is unconfirmed and it is not published here.', 'informational', 'needs_confirmation', 'https://ftmo.com/fr/comparison-table/', timestamptz '2026-09-04', 8),
  ('ftmo', null, 'market', 'Futures is a separate product', 'FTMO Futures is in beta with its own rules. No CFD rule on this page applies to it.', 'informational', 'needs_confirmation', 'https://ftmo.com/en/futures/', timestamptz '2026-09-04', 9);


-- 6. CONTROLE
-- Attendu : 3 programmes, 37 plans, 1 promo, 9 regles.
select p.name, p.market, p.status, pl.variant_label, pl.phase, pl.account_size,
       pl.regular_price, pl.currency, pl.profit_target, pl.daily_loss_limit,
       pl.best_day_rule, pl.consistency_rule, pl.profit_split
from firm_programs p left join firm_program_plans pl on pl.program_id = p.id
where p.firm_slug = 'ftmo'
order by p.sort_order, pl.variant_key nulls first, pl.account_size, pl.phase;
