import { PropFirm, Promotion } from '@/types'

// Sample data - À remplacer par les données Supabase
export const samplePropFirms: PropFirm[] = [
  {
    id: '1',
    name: 'FTMO',
    slug: 'ftmo',
    logo_url: 'https://logo.clearbit.com/ftmo.com',
    website_url: 'https://ftmo.com',
    min_price: 155,
    max_price: 1080,
    challenge_types: ['2-step'],
    account_sizes: [10000, 25000, 50000, 100000, 200000],
    profit_split: 80,
    profit_target_phase1: 10,
    profit_target_phase2: 5,
    max_daily_drawdown: 5,
    max_total_drawdown: 10,
    allows_scalping: true,
    allows_news_trading: true,
    allows_weekend_holding: true,
    allows_hedging: true,
    min_trading_days: 4,
    platforms: ['MT4', 'MT5', 'cTrader'],
    trustpilot_score: 4.8,
    trustpilot_reviews: 6500,
    year_founded: 2015,
    is_regulated: false,
    regulation_info: null,
    payout_methods: ['Bank Transfer', 'Crypto', 'Skrill'],
    min_payout: 500,
    payout_frequency: 'Bi-weekly',
    affiliate_link: 'https://ftmo.com/?ref=propfirmscanner',
    affiliate_commission: 15,
    created_at: '2024-01-01',
    updated_at: '2024-01-15',
  },
  {
    id: '2',
    name: 'Funded Next',
    slug: 'funded-next',
    logo_url: 'https://logo.clearbit.com/fundednext.com',
    website_url: 'https://fundednext.com',
    min_price: 32,
    max_price: 999,
    challenge_types: ['1-step', '2-step'],
    account_sizes: [6000, 15000, 25000, 50000, 100000, 200000],
    profit_split: 90,
    profit_target_phase1: 10,
    profit_target_phase2: 5,
    max_daily_drawdown: 5,
    max_total_drawdown: 10,
    allows_scalping: true,
    allows_news_trading: true,
    allows_weekend_holding: true,
    allows_hedging: true,
    min_trading_days: 5,
    platforms: ['MT4', 'MT5'],
    trustpilot_score: 4.6,
    trustpilot_reviews: 4200,
    year_founded: 2022,
    is_regulated: false,
    regulation_info: null,
    payout_methods: ['Bank Transfer', 'Crypto', 'Rise'],
    min_payout: 100,
    payout_frequency: 'Bi-weekly',
    affiliate_link: 'https://fundednext.com/?ref=propfirmscanner',
    affiliate_commission: 12,
    created_at: '2024-01-01',
    updated_at: '2024-01-15',
  },
  {
    id: '3',
    name: 'E8 Funding',
    slug: 'e8-funding',
    logo_url: 'https://logo.clearbit.com/e8funding.com',
    website_url: 'https://e8funding.com',
    min_price: 138,
    max_price: 988,
    challenge_types: ['1-step', '2-step'],
    account_sizes: [25000, 50000, 100000, 250000],
    profit_split: 80,
    profit_target_phase1: 8,
    profit_target_phase2: 5,
    max_daily_drawdown: 5,
    max_total_drawdown: 8,
    allows_scalping: true,
    allows_news_trading: false,
    allows_weekend_holding: true,
    allows_hedging: true,
    min_trading_days: 0,
    platforms: ['MT4', 'MT5'],
    trustpilot_score: 4.5,
    trustpilot_reviews: 3100,
    year_founded: 2021,
    is_regulated: false,
    regulation_info: null,
    payout_methods: ['Bank Transfer', 'Crypto'],
    min_payout: 100,
    payout_frequency: 'On-demand',
    affiliate_link: 'https://e8funding.com/?ref=propfirmscanner',
    affiliate_commission: 10,
    created_at: '2024-01-01',
    updated_at: '2024-01-15',
  },
  {
    id: '4',
    name: 'The Funded Trader',
    slug: 'the-funded-trader',
    logo_url: 'https://logo.clearbit.com/thefundedtrader.com',
    website_url: 'https://thefundedtrader.com',
    min_price: 65,
    max_price: 949,
    challenge_types: ['1-step', '2-step', 'instant-funding'],
    account_sizes: [5000, 10000, 25000, 50000, 100000, 200000, 400000],
    profit_split: 90,
    profit_target_phase1: 10,
    profit_target_phase2: 5,
    max_daily_drawdown: 5,
    max_total_drawdown: 10,
    allows_scalping: true,
    allows_news_trading: true,
    allows_weekend_holding: true,
    allows_hedging: true,
    min_trading_days: 3,
    platforms: ['MT4', 'MT5', 'cTrader'],
    trustpilot_score: 4.4,
    trustpilot_reviews: 5800,
    year_founded: 2021,
    is_regulated: false,
    regulation_info: null,
    payout_methods: ['Bank Transfer', 'Crypto', 'PayPal'],
    min_payout: 50,
    payout_frequency: 'Bi-weekly',
    affiliate_link: 'https://thefundedtrader.com/?ref=propfirmscanner',
    affiliate_commission: 10,
    created_at: '2024-01-01',
    updated_at: '2024-01-15',
  },
  {
    id: '5',
    name: 'True Forex Funds',
    slug: 'true-forex-funds',
    logo_url: 'https://logo.clearbit.com/trueforexfunds.com',
    website_url: 'https://trueforexfunds.com',
    min_price: 59,
    max_price: 899,
    challenge_types: ['1-step', '2-step'],
    account_sizes: [10000, 25000, 50000, 100000, 200000],
    profit_split: 80,
    profit_target_phase1: 8,
    profit_target_phase2: 5,
    max_daily_drawdown: 5,
    max_total_drawdown: 10,
    allows_scalping: true,
    allows_news_trading: true,
    allows_weekend_holding: true,
    allows_hedging: true,
    min_trading_days: 5,
    platforms: ['MT4', 'MT5'],
    trustpilot_score: 4.3,
    trustpilot_reviews: 2400,
    year_founded: 2021,
    is_regulated: false,
    regulation_info: null,
    payout_methods: ['Bank Transfer', 'Crypto'],
    min_payout: 100,
    payout_frequency: 'Bi-weekly',
    affiliate_link: 'https://trueforexfunds.com/?ref=propfirmscanner',
    affiliate_commission: 8,
    created_at: '2024-01-01',
    updated_at: '2024-01-15',
  },
  {
    id: '6',
    name: 'Topstep',
    slug: 'topstep',
    logo_url: 'https://logo.clearbit.com/topstep.com',
    website_url: 'https://topstep.com',
    min_price: 165,
    max_price: 375,
    challenge_types: ['1-step'],
    account_sizes: [50000, 100000, 150000],
    profit_split: 90,
    profit_target_phase1: 6,
    profit_target_phase2: null,
    max_daily_drawdown: 4,
    max_total_drawdown: 5,
    allows_scalping: true,
    allows_news_trading: true,
    allows_weekend_holding: false,
    allows_hedging: false,
    min_trading_days: 0,
    platforms: ['NinjaTrader', 'TradingView', 'Tradovate'],
    trustpilot_score: 4.7,
    trustpilot_reviews: 8200,
    year_founded: 2012,
    is_regulated: true,
    regulation_info: 'US-based, NFA regulated',
    payout_methods: ['Bank Transfer', 'ACH'],
    min_payout: 50,
    payout_frequency: 'Weekly',
    affiliate_link: 'https://topstep.com/?ref=propfirmscanner',
    affiliate_commission: 20,
    created_at: '2024-01-01',
    updated_at: '2024-01-15',
  },
]

export const samplePromotions: Promotion[] = [
  {
    id: '1',
    prop_firm_id: '1',
    code: 'SCANNER20',
    discount_percent: 20,
    discount_amount: null,
    description: '20% off all challenges',
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    is_active: true,
  },
  {
    id: '2',
    prop_firm_id: '2',
    code: 'FUNDED25',
    discount_percent: 25,
    discount_amount: null,
    description: '25% off first challenge',
    valid_from: '2024-01-01',
    valid_until: '2024-06-30',
    is_active: true,
  },
  {
    id: '3',
    prop_firm_id: '4',
    code: 'TFT15',
    discount_percent: 15,
    discount_amount: null,
    description: '15% off all accounts',
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    is_active: true,
  },
]

export function getPromotionForFirm(firmId: string): Promotion | undefined {
  return samplePromotions.find(p => p.prop_firm_id === firmId && p.is_active)
}
