// Textes d'INTERFACE de la page firme (anglais, pilote). Aucun texte metier :
// tout ce qui decrit une firme vient de sa fiche. Les fonctions recoivent le nom
// de la firme ou une valeur de la fiche, jamais une valeur ecrite ici.

import type { StatutManquant } from '@/lib/firm-profile'

export const COPY = {
  hero: {
    badge: (type: string) => `${type} prop firm`,
    trustpilot: 'Trustpilot',
    external: 'External',
    choose: 'Choose your program',
    rules: 'See the key rules',
    logoLabel: (nom: string, code: string | null) => (code ? `Visit ${nom} with code ${code}` : `Visit ${nom}`),
  },
  commercial: {
    popular: 'Most popular plan',
    off: 'off',
    code: 'Exclusive code',
    claim: 'Claim deal',
    from: 'From',
    configure: 'Configure my account',
  },
  price: {
    monthly: '/month',
  },
  copy: {
    idle: 'Copy code',
    short: 'Copy',
    done: 'Copied',
    failed: 'Select the code',
  },
  knownFor: (nom: string) => `What ${nom} is known for`,
  quick: {
    title: 'Quick information',
    platforms: 'Platforms',
    dataFeeds: 'Data feeds',
    purchase: 'Purchase methods',
    profile: 'Trading profile',
    leverage: 'Leverage',
  },
  configurator: {
    eyebrow: 'Account configurator',
    title: 'Find the program that fits you',
    intro: 'Start with your goal. Price and rules update as you choose.',
    market: 'Choose your market',
    program: 'How do you want to be funded?',
    variant: 'Choose your variant',
    size: 'Pick your account size',
    plateforme: 'Choose your platform',
    data_feed: 'Choose your data feed',
    programs: (n: number) => `${n} program${n > 1 ? 's' : ''}`,
    sizes: (n: number) => `${n} size${n > 1 ? 's' : ''}`,
    fromPrice: (prix: string) => `from ${prix}`,
    standard: 'Standard',
    selection: 'Your selection',
    withCode: (remise: string, code: string) => `${remise} with ${code}`,
    continueTo: (nom: string) => `Continue to ${nom}`,
    notListed: (code: string) => `Code ${code} is not listed for this selection.`,
    evaluation: 'Evaluation',
    noEvaluation: 'No evaluation',
  },
  comparison: {
    title: 'Which program fits you?',
    intro: 'A comparison, not a second decision — choosing here updates the configurator above.',
    selected: 'Selected',
    choose: 'Choose this program',
    maxAccounts: 'Max funded accounts',
  },
  rules: {
    eyebrow: 'Rules by phase',
    title: (programme: string, plusieurs: boolean, phase: string) =>
      plusieurs ? `${programme}: rules by phase` : `${programme}: ${phase.toLowerCase()} rules`,
    intro: 'Only the rules of the current selection appear here.',
    rule: 'Rule',
    value: (phase: string) => `${phase} value`,
    meaning: 'Meaning',
  },
  modules: {
    journeyEyebrow: 'How it works',
    journeyTitle: 'From evaluation to your first payout',
    trainingEyebrow: 'Included value',
    trainingTitle: 'Training included',
    accountsEyebrow: 'After you pass',
    accountsTitle: 'Accounts available after you pass',
  },
  conditions: {
    eyebrow: 'Before you buy',
    title: 'Trading and payout conditions',
    trading: 'Trading',
    tradingSub: 'Assets, leverage and permissions',
    fees: 'Fees',
    feesSub: 'Every fee tied to one account',
    payouts: 'Payouts',
    payoutsSub: 'Payout policy',
    payoutMethods: 'Payout methods',
    provider: 'Provider',
  },
  about: {
    title: (nom: string) => `About ${nom}`,
    founded: 'Founded',
    country: 'Country',
    ceo: 'CEO / Founder',
    type: 'Firm type',
  },
  strengths: {
    eyebrow: 'Honest view',
    title: (nom: string) => `${nom}: strengths and things to know`,
    intro: 'Our independent analysis, based on verified official rules and documents.',
    pros: 'Strengths',
    cons: 'Things to know',
  },
  verdict: {
    eyebrow: 'PropFirmScanner verdict',
    title: (nom: string) => `Who we recommend ${nom} for`,
    ours: 'Our verdict',
    notFor: 'Consider another firm if…',
  },
  faq: {
    eyebrow: 'FAQ',
    title: 'Frequently asked questions',
  },
  final: {
    title: 'Ready to pick your program?',
    intro: 'Configure your account and check the rules one last time before payment.',
    button: 'Configure my account',
  },
  mobile: {
    continue: 'Continue',
    claim: 'Claim deal',
  },
  none: 'None',
  statut: {
    not_published: 'Not published',
    not_applicable: 'Not applicable',
    needs_confirmation: 'Needs confirmation',
    source_conflict: 'Sources conflict',
  } satisfies Record<StatutManquant, string>,
} as const
