// Textes d'INTERFACE de la page firme (anglais), repris du contrat visuel
// « PropFirmScanner Universal Virgin Template » (19 septembre 2026). Aucun texte
// metier : tout ce qui decrit une firme vient de sa fiche. Les fonctions
// recoivent le nom de la firme ou une valeur de la fiche, jamais une valeur
// ecrite ici.

import type { StatutManquant } from '@/lib/firm-profile'

export const COPY = {
  hero: {
    badge: (type: string) => `${type} prop firm`,
    trustpilot: 'Trustpilot',
    outOf: '/ 5',
    reviews: (n: string) => `${n} reviews`,
    founded: 'Founded',
    country: 'Country',
    founder: 'CEO / Founder',
    choose: 'Choose your program',
    rules: 'See the key rules',
  },
  commercial: {
    popular: 'Most popular plan',
    off: 'off',
    code: 'Promo code',
    claim: 'Claim deal',
    continueTo: (nom: string) => `Continue to ${nom}`,
    from: 'From',
  },
  price: {
    monthly: '/month',
  },
  copy: {
    idle: 'Copy code',
    done: 'Copied',
    failed: 'Select the code',
  },
  knownFor: (nom: string) => `What ${nom} is known for`,
  info: {
    title: 'Firm information',
    platforms: 'Selectable platforms',
    markets: 'Tradable markets',
    dataFeeds: 'Data feeds',
    purchase: 'Purchase methods',
    profile: 'Trading profile',
    leverage: 'Leverage',
  },
  configurator: {
    eyebrow: 'Account configurator',
    title: 'Find the program that fits you',
    intro: 'Start with your goal. Price and rules update as you choose.',
    market: 'Choose your market',
    program: 'Choose your funding route',
    variant: 'Choose your variant',
    size: 'Pick your account size',
    plateforme: 'Choose your platform',
    data_feed: 'Choose your data feed',
    programs: (n: number) => `${n} program${n > 1 ? 's' : ''}`,
    sizes: (n: number) => `${n} size${n > 1 ? 's' : ''}`,
    fromPrice: (prix: string) => `from ${prix}`,
    standard: 'Standard',
    selection: 'Your selection',
    phases: 'Phases',
    withCode: (remise: string, code: string) => `${remise} with ${code}`,
    notListed: (code: string) => `Code ${code} is not listed for this selection.`,
    evaluation: 'Evaluation',
    noEvaluation: 'No evaluation',
  },
  comparison: {
    eyebrow: 'Program comparison',
    title: 'Which program fits you?',
    intro: 'One card per program. Choosing one updates the configurator.',
    selected: 'Selected',
    program: 'Program',
    maxAccounts: 'Max funded accounts',
  },
  rules: {
    eyebrow: 'Rules',
    title: 'Rules by programme and phase',
    intro: 'Rules follow the selected programme, account size, variant and phase.',
    plan: 'Selected commercial plan',
    programme: 'Programme',
    phase: 'Phase',
    rule: 'Rule',
    status: 'Status',
    meaning: 'What it means',
  },
  modules: {
    journeyEyebrow: 'How it works',
    journeyTitle: 'From evaluation to your first payout',
    includedEyebrow: 'Included',
    includedTitle: 'What else is included?',
    training: 'Training',
    accounts: 'Accounts after you pass',
  },
  conditions: {
    eyebrow: 'Trading and payout conditions',
    title: 'Everything to understand before buying',
    intro: 'For the selected programme and account size.',
    trading: 'Trading',
    tradingTitle: 'Assets, platforms and permissions',
    fees: 'Fees',
    feesTitle: 'Activation, resets and trading costs',
    payouts: 'Payouts',
    payoutsTitle: 'Payout policy',
    provider: 'Provider',
    methods: 'Methods',
    breach: 'Breach',
    showAll: (n: number) => `Show all ${n} rules`,
    showLess: 'Show fewer rules',
  },
  verdict: {
    title: 'PropFirmScanner verdict',
    bestFor: 'Best for',
    thingsToKnow: 'Things to know',
  },
  faq: {
    eyebrow: 'FAQ',
    title: 'Frequently asked questions',
  },
  final: {
    eyebrow: 'Ready to continue?',
    title: (nom: string) => `Build your ${nom} selection`,
  },
  similar: {
    eyebrow: 'Similar firms',
    title: 'Compare other firms with an available partner deal',
    view: 'View firm',
    off: (remise: number) => `${remise}% off`,
  },
  none: 'None',
  statut: {
    confirmed: 'confirmed',
    not_published: 'Not published',
    not_applicable: 'Not applicable',
    needs_confirmation: 'Needs confirmation',
    source_conflict: 'Sources conflict',
  } satisfies Record<StatutManquant | 'confirmed', string>,
} as const
